yamlCopy code
# config/services.yaml

services:
    # configuration de SwiftMailer
    Swiftmailer\Swift_Mailer:
        arguments: ['@Swiftmailer\Transport']
    Swiftmailer\Transport:
        class: Swift_SmtpTransport
        arguments:
            - '%env(MAILER_HOST)%'
            - '%env(MAILER_PORT)%'
            - '%env(MAILER_ENCRYPTION)%'
            - '%env(MAILER_USER)%'
            - '%env(MAILER_PASSWORD)%'